name: autofix.ci

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup PMPM
        uses: pnpm/action-setup@v6
        with:
          version: 10.33.2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      
      - name: Install dependencies
        run: pnpm add -D oxfmt
      
      - name: Run formatter
        run: pnpm dlx oxfmt
      
      - name: Run autofix.ci
        uses: autofix-ci/action@v1
