name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}

      - name: Run autofmt
        uses: area44/autofmt@d2c585d7e412b237cde77b054c680835fc5d3999 # v0.1.0
